# Site settings
title: "Dasom Kim Resume"
description: "Dasom Kim Resume"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Dasom Kim"
resume_title:                   "AI Engineer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "dasom.ruby.kim@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "010-2661-9478"
resume_contact_address:         "Yeongtong-gu, Suwon, South Korea"

resume_header_contact_info:     "010-2661-9478 • dasom.ruby.kim@gmail.com"
display_header_contact_info:    "true"

resume_header_intro: "문제 해결능력, 빠른 습득이 장점인 개발자 입니다. AI Voice Assistant와 관련된 AI 기술의 상품화 경험이 있습니다. 데이터 구축, Github, CI tool, Docker를 이용한 모델 학습 및 평가 파이프라인 개발, AWS를 이용한 서빙까지 상품화를 위한 다양한 Skill을 보유하고있습니다. 현재는 삼성 휴대폰의 Bixby라는 음성인식 서비스에서, RAG를 이용한 서비스 개발 업무를 리딩하고있습니다."

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "no"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
# resume_section_recognition:     true
# resume_section_links:           true
# resume_section_associations:    true
resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  # resume_github_url:            "https://github.com/Ujutokki"
  # resume_twitter_url:           "http://twitter.com/jglovier"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/kimdasomee"
  # resume_instagram_url:         "insert your Instagram URL here"
  # resume_website_url:           "http://joelglovier.com"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
